
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  major: 1
  minor: 0
  majorDotMinor: '$(major).$(minor)'
  revision: $[counter(variables['majorDotMinor'], 0)]

steps:
- template: Build-Steps.yml
  parameters:
    BuildConfiguration: $(buildConfiguration)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: bin'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\Exdi\exdigdbsrvsample\$(buildConfiguration)'
