
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'
  major: 1
  minor: 1
  majorDotMinor: '$(major).$(minor)'
  revision: $[counter(variables['majorDotMinor'], 0)]

steps:
- template: Build-Steps.yml
  parameters:
    BuildConfiguration: $(buildConfiguration)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: bin'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\Exdi\exdigdbsrv\$(buildConfiguration)'

- task: PublishSymbols@2
  displayName: 'Source index symbols 2'
  inputs:
    SearchPattern: '$(Build.SourcesDirectory)\Exdi\exdigdbsrv\$(buildConfiguration)\**\*.pdb'
    SymbolServerType: 'TeamServices'

- task: ms-vscs-artifact.build-tasks.artifactSymbolTask-1.artifactSymbolTask@0
  displayName: 'Publish to Symbols to Artifact Services'
  inputs:
    symbolServiceURI: 'https://microsoft.artifacts.visualstudio.com/DefaultCollection'
    requestName: 'DebuggingExperiences/$(Build.BuildNumber)/$(Build.BuildId)'
    sourcePath: '$(Build.SourcesDirectory)\Exdi\exdigdbsrv'
    expirationInDays: '365'
